module.exports = {
  config: {
    name: "cute",
    version: "1.0.0",
    author: "Hridoy",
    role: 0,
    shortDescription: "Random cute image/video",
    category: "Image",
    guide: "{pn}",
    cooldown: 5
  },

  onStart: async function ({ api, event }) {

    const links = [
      "https://files.catbox.moe/rzns7w.jpeg",
      "https://files.catbox.moe/uzy3kv.jpeg",
      "https://files.catbox.moe/oi25nr.jpeg",
      "https://files.catbox.moe/pr7v0v.jpeg",
      "https://files.catbox.moe/yhlaek.jpeg",
      "https://files.catbox.moe/lh7c6s.jpeg",
      "https://files.catbox.moe/ykgaeb.jpeg",
      "https://files.catbox.moe/c39qmg.jpeg",
      "https://files.catbox.moe/ljdvvv.jpeg",
      "https://files.catbox.moe/4z4hvs.jpeg",
      "https://files.catbox.moe/z4fgu8.jpeg",
      "https://files.catbox.moe/46l4u2.jpeg",
      "https://files.catbox.moe/awk48s.jpeg",
      "https://files.catbox.moe/szbfjb.jpeg",
      "https://files.catbox.moe/wqt6oe.jpeg",
      "https://files.catbox.moe/bd1s9o.jpeg",
      "https://files.catbox.moe/i8i6vi.jpeg",
      "https://files.catbox.moe/afyg2a.jpeg",
      "https://files.catbox.moe/6nf05l.jpeg",
      "https://files.catbox.moe/eo3fzs.jpeg",
      "https://files.catbox.moe/g6va7z.jpeg",
      "https://files.catbox.moe/xjdjtz.jpeg",
      "https://files.catbox.moe/t98jnw.jpeg",
      "https://files.catbox.moe/ts33z5.jpeg",
      "https://files.catbox.moe/bepkke.jpeg",
      "https://files.catbox.moe/yowox3.jpeg",
      "https://files.catbox.moe/ttilkr.jpeg",
      "https://files.catbox.moe/7ix8lq.jpeg",
      "https://files.catbox.moe/9inww0.jpeg",
      "https://files.catbox.moe/bvvniw.jpeg",
      "https://files.catbox.moe/y73h9q.jpeg",
      "https://files.catbox.moe/t3if71.jpeg",
      "https://files.catbox.moe/0bk6ya.jpeg",
      "https://files.catbox.moe/njohy0.jpeg",
      "https://files.catbox.moe/nozun9.jpeg",
      "https://files.catbox.moe/4h597z.jpeg",
      "https://files.catbox.moe/f6tm7h.jpeg",
      "https://files.catbox.moe/j8g96g.jpeg",
      "https://files.catbox.moe/5kh3ps.jpeg",
      "https://files.catbox.moe/dhgok4.jpeg",
      "https://files.catbox.moe/nl6he9.jpeg",
      "https://files.catbox.moe/nk6k7q.jpeg",
      "https://files.catbox.moe/afc1b3.jpeg",
      "https://files.catbox.moe/ns2xf9.jpeg",
      "https://files.catbox.moe/rxer26.jpeg",
      "https://files.catbox.moe/v0g5tb.jpeg",
      "https://files.catbox.moe/w2c7f6.jpeg",
      "https://files.catbox.moe/4vafsu.jpeg",
      "https://files.catbox.moe/mb0xqo.jpeg",
      "https://files.catbox.moe/we7e28.jpeg",
      "https://files.catbox.moe/5b9y1w.jpeg",
      "https://files.catbox.moe/cbdyy4.jpeg",
      "https://files.catbox.moe/l9gtc5.jpeg",
      "https://files.catbox.moe/tfndm9.jpeg",
      "https://files.catbox.moe/bei4vl.jpeg",
      "https://files.catbox.moe/p01uq0.jpeg",
      "https://files.catbox.moe/pb4jg2.jpeg",
      "https://files.catbox.moe/kax9ho.jpeg",
      "https://files.catbox.moe/sm07n1.jpeg",
      "https://files.catbox.moe/l6otcl.jpeg",
      "https://files.catbox.moe/degu36.jpeg",
      "https://files.catbox.moe/89eykk.jpeg",
      "https://files.catbox.moe/usubed.jpeg",
      "https://files.catbox.moe/s1wa5o.jpeg",
      "https://files.catbox.moe/oxhzwx.jpeg",
      "https://files.catbox.moe/hqnw98.jpeg",
      "https://files.catbox.moe/3rryrx.jpeg",
      "https://files.catbox.moe/wo8tjb.jpeg",
      "https://files.catbox.moe/34f0ua.jpeg",
      "https://files.catbox.moe/g127k9.jpeg",
      "https://files.catbox.moe/txhsbf.jpeg",
      "https://files.catbox.moe/b1al3f.jpeg",
      "https://files.catbox.moe/kwcm1x.jpeg",
      "https://files.catbox.moe/mhfsaq.jpeg",
      "https://files.catbox.moe/u7umss.jpeg",
      "https://files.catbox.moe/862gr2.jpeg",
      "https://files.catbox.moe/yy0el3.jpeg",
      "https://files.catbox.moe/f72gxc.jpeg",
      "https://files.catbox.moe/gf7ywx.jpeg",
      "https://files.catbox.moe/8kzpoa.jpeg",
      "https://files.catbox.moe/sv6thc.jpeg",
      "https://files.catbox.moe/5kxgu1.jpeg",
      "https://files.catbox.moe/klkok4.jpeg",
      "https://files.catbox.moe/tlwrz8.jpeg",
      "https://files.catbox.moe/7xgfqi.jpeg",
      "https://files.catbox.moe/qq0bba.jpeg",
      "https://files.catbox.moe/bmbw6h.jpeg",
      "https://files.catbox.moe/x5v5iw.jpeg",
      "https://files.catbox.moe/uprsya.jpeg",
      "https://files.catbox.moe/rjhl5a.jpeg",
      "https://files.catbox.moe/ace6rs.jpeg",
      "https://files.catbox.moe/35qpk7.jpeg",
      "https://files.catbox.moe/xj5df8.jpeg",
      "https://files.catbox.moe/7uk36r.jpeg",
      "https://files.catbox.moe/wzklpy.jpeg",
      "https://files.catbox.moe/yaoe0a.jpeg",
      "https://files.catbox.moe/1s0em5.jpeg",
      "https://files.catbox.moe/82rqkc.jpeg",
      "https://files.catbox.moe/5z37vm.jpeg",
      "https://files.catbox.moe/episma.jpeg",
      "https://files.catbox.moe/u7na9u.jpeg",
      "https://files.catbox.moe/dq64k6.jpeg",
      "https://files.catbox.moe/m9x6hr.jpeg",
      "https://files.catbox.moe/kdn7is.jpeg",
      "https://files.catbox.moe/xqii9x.jpeg",
      "https://files.catbox.moe/dsey1x.jpeg",
      "https://files.catbox.moe/116jj0.jpeg",
      "https://files.catbox.moe/ukpuq3.jpeg",
      "https://files.catbox.moe/6sywvn.jpeg",
      "https://files.catbox.moe/1aroew.jpeg",
      "https://files.catbox.moe/q18itr.jpeg",
      "https://files.catbox.moe/kw9e5h.jpeg",
      "https://files.catbox.moe/6h9j2t.jpeg",
      "https://files.catbox.moe/k8f5gu.jpeg",
      "https://files.catbox.moe/0w7fgw.jpeg",
      "https://files.catbox.moe/gfkx5h.jpeg",
      "https://files.catbox.moe/ycer6n.jpeg",
      "https://files.catbox.moe/r9gzb5.jpeg",
      "https://files.catbox.moe/fg1oq8.jpeg",
      "https://files.catbox.moe/pg7p9f.jpeg",
      "https://files.catbox.moe/jtlqbg.jpeg",
      "https://files.catbox.moe/kquf3m.jpeg",
      "https://files.catbox.moe/m2snca.jpeg",
      "https://files.catbox.moe/vr08al.jpeg",
      "https://files.catbox.moe/8moh53.jpeg",
      "https://files.catbox.moe/48uo1z.jpeg",
      "https://files.catbox.moe/33pt2n.jpeg",
      "https://files.catbox.moe/052j8v.jpeg",
      "https://files.catbox.moe/31ua3a.jpeg",
      "https://files.catbox.moe/z1fumj.jpeg",
      "https://files.catbox.moe/w66iy2.jpeg",
      "https://files.catbox.moe/tugoxa.jpeg",
      "https://files.catbox.moe/7f0zzz.jpeg",
      "https://files.catbox.moe/3yde64.jpeg",
      "https://files.catbox.moe/6tt163.jpeg",
      "https://files.catbox.moe/gm7tjd.jpeg",
      "https://files.catbox.moe/0j86jl.jpeg",
      "https://files.catbox.moe/kb6poj.jpeg",
      "https://files.catbox.moe/y5qmd2.jpeg",
      "https://files.catbox.moe/mb6jim.jpeg",
      "https://files.catbox.moe/icrts2.mp4",
      "https://files.catbox.moe/onl62p.jpeg",
      "https://files.catbox.moe/j1rd34.jpeg",
      "https://files.catbox.moe/dkml0p.jpeg",
      "https://files.catbox.moe/hp21zv.jpeg",
      "https://files.catbox.moe/v4m9oa.jpeg",
      "https://files.catbox.moe/0sjnak.jpeg",
      "https://files.catbox.moe/6n6ry7.jpeg",
      "https://files.catbox.moe/w7nvca.jpeg",
      "https://files.catbox.moe/zkwqaf.jpeg",
      "https://files.catbox.moe/drt16o.jpeg",
      "https://files.catbox.moe/ocbt5p.jpeg",
      "https://files.catbox.moe/mq7pix.jpeg",
      "https://files.catbox.moe/4bkoio.jpeg",
      "https://files.catbox.moe/bxv6k4.jpeg",
      "https://files.catbox.moe/0oyaro.jpeg",
      "https://files.catbox.moe/09neun.jpeg",
      "https://files.catbox.moe/obschb.jpeg",
      "https://files.catbox.moe/yjhce9.jpeg",
      "https://files.catbox.moe/1mr837.jpeg",
      "https://files.catbox.moe/r833h6.jpeg",
      "https://files.catbox.moe/wcd10p.jpeg",
      "https://files.catbox.moe/2h4xrx.jpeg",
      "https://files.catbox.moe/t73inn.jpeg",
      "https://files.catbox.moe/52a3iq.jpeg"
    ];

    try {
      const randomLink = links[Math.floor(Math.random() * links.length)];
      const stream = await global.utils.getStreamFromURL(randomLink);

      return api.sendMessage({
        body: "💖 Cute Photo Just For You 😘",
        attachment: stream
      }, event.threadID, event.messageID);

    } catch (err) {
      console.error(err);
      return api.sendMessage("⚠️ Cute pic load hoilo na... abar try koro 😅", event.threadID, event.messageID);
    }
  }
};
